[package]
name = "linkbot"
version = "0.0.2"
authors = ["David Ko <david@barobo.com>"]

description = "Rust API for controlling Barobo Linkbots."

homepage = "https://barobo.com"
repository = "https://github.com/davidko/linkbot-rs"
license = "GPL-3.0"

[dependencies]
libc = "0.2.23"
